name: Zombiesurvival
version: 1.0.0
main: main.Main
api-version: 1.19
authors: [ Barity_ ]
depend: [ ProtocolLib ]
description: Wave-Zombie-Defence survival since 2020
commands:
  items:
    description: 커스텀 아이템 리스트 명령어
  game:
    description: 게임 명령어
  help:
    description: 도움 명령어
  vw:
    description: 호환되지 않는 버전 안내 명령어
  wave:
    description: 웨이브 설정 명령어
  spectator:
    description: 관전자 명령어
    aliases: [ spec ]